### PR TITLE
Remove appdmg from dependencies

### LINKED ISSUE #507: npm error on linux
I've been making more than enough issues, and I've wanted to contribute, but I have the following error when trying to build.

I ran these commands:

```
git clone https://github.com/ghostery/user-agent-desktop/
cd user-agent-desktop
npm ci
```

I got the error at https://gist.github.com/2br-2b/8c5d9f7f0f683f3671ae7a8c844465ce

What is going wrong? I assumed it was an error with the wrong version of python with some feature not included in this version of python, hence the error `platform is not implemented yet`.

I'm running Linux Mint, and it seems to be trying to work with some macos files. I'm guessing that whatever it's trying to do is not supported on Linux and only on Macs and/or Windows.

This will be my first time contributing to Firefox or any of its forks, so I want to make sure I get the environment set up right.

Thank you for your help!

_Originally posted by @2br-2b in https://github.com/ghostery/user-agent-desktop/discussions/497_

### PR DESCRIPTION
**Pull request by chrmod**
appdmg was causing issue on some Linux system and as we only need it on MacOS we can access it via npx

fix #507

### CODE REVIEW

**Review by remusao — APPROVED** [review]

File: fern/core/addons.js [hunk 1]
```diff
@@ -1,6 +1,7 @@
 const stream = require("stream");
 const path = require("path");
 const fs = require("fs");
+const md5 = require("md5");
```
Comment (remusao) [inline fern/core/addons.js:4]: In principle I think we should be able to use the standard module https://nodejs.org/api/crypto.html for that?

Comment (remusao) [reply fern/core/addons.js:4]: For example:
```js
const crypto = require('crypto');

const getAddonUrlHash = url => crypto.createHash('md5').update(url).digest("hex");
```

Comment (chrmod) [reply fern/core/addons.js]: yeah, good point

**Review by remusao — APPROVED** [review]
